### ISSUE TITLE
Disable or Remove

### ISSUE THREAD

**Issue by LibertyType** [zar-nicolas20/GlyphsApp-Package-Install#1]
I installed this today and find I do not like the way it is organized.

How about instructions on disabling and removing everything it installed?

Thanks,

George Thomas

**Comment by zar-nicolas20** [comment]
Hi George,

You should deleted the symbolic links that were created at `~/Library/Application\ Support/Glyphs/Scripts/` and then deleted the GlyphsScripts directory created at `~/Documents/GlyphsScripts/`,
that is all.

If you want to deleted what was written in `/etc/cron.d` you only need to type in terminal 

```
sudo rm /private/etc/cron.d/sync_git_repos
```

and put your user password. This step is automatic when you try to install again.

Tell me how it was installed in your machine? I have three machines and this is installed in alls in the same way. Are you working in El Capitán or Yosemite?

Best,

Nicolás

**Comment by LibertyType** [comment]
Hi Nicolás:

Running El Capital 10.11.1. I installed it using your instructions in 
the Read-me file.

I think the script is a great idea but I just didn't like the way it was 
organized and presented after installation, i.e. by author. I have all 
my Glyphs scripts organized based on the category of task they automate. 
That's what works best for me because with so many authors doing scripts 
it's almost impossible to remember who wrote what.

Thanks for the info on de-installing.

Best regards,

George Thomas

**Comment by zar-nicolas20** [comment]
You are right,

Organizing by author allows me to see from where is coming the script. If you want you can suggest me your ideal organization and I will write a bash shell script following that structure.

Best,

Nicolás

**Comment by LibertyType** [comment]
Hi Nicolás:

I have them arranged in folders as shown, pretty much using the same 
structure Rainer did originally. There are several scripts which aren't 
in a folder because they are singletons in their category. The folder GS 
contains those written by Georg Siefert. When I first got Glyphs the 
scripts were pretty much only by Rainer and Georg which is why I have 
them separated. I should move his to categories like the rest.

Accents
Align
Anchors
Arabic
Audits
Bubblekern
Color Labels
Compare UFOs.py
Components
Effects
Export InDesign Tagged Text.py
Features
Find Unicode Codepoint.scpt
Font
Glyph Names
Glyphs
GS
Guidelines
Hinting
Images
Key Characters
Masters
Metrics
Nudge-Move by Numerical Value.py
OpenType
Outline Check
Paths
Pixelfonts
Select
Selection
Sketching
Smallcaps
StringSmash
Stylistic Sets

I look forward to seeing what you produce.

Best regards,

George Thomas

**Comment by pocholito** [comment]
Hola Nicolás

Espero que estes muy bien.
Bajé tus scripts porque la idea de que se pueda instalar todo de una vez me parecía super apropiada.
Quite pasarte unos comentarios pero no entiendo donde ponerlos, así que te envío este mail.

Seguí las instrucciones en terminal.
Todo se instalé bien.
Cerre glyphs y lo volví a abrir, y se quedó colgado.

Saque la carpeta > GlyphsScripts de usuario/documents
y volvió a funcionar.

Lo extraño es que siguen apareciendo los script en sus lugares
aunque la carpeta este fuera del user.

No se si te sirve de algo,
sods, darío

**Comment by zar-nicolas20** [comment]
Hola Darío,

Me intriga que se haya quedado colgado.

Bien, para desinstalarlo es como hiciste, borrando la carpeta de GlyphScripts en Documentos, y luego borrando los enlaces que fueron creados en la carpeta de script y filtros de Glyphs.

Puedes intentar instalarlo de nuevo, borrando todo el contenido que se encuentran en filtros y script, respalda primero su contenido). El único script que no se instala es el de RMX porque ese filtro no se distribuye a través de GitHub.

Tu comentario fue puesto en el lugar apropiado en GitHub, pero no puedes acceder a comentarios anteriores. Voy a copiar acá el proceso de borrado de los scripts instalados.

Cualquier otra consulta no dudes en escribirme de nuevo. Voy a tratar de reproducir lo que te pasó con el script para arreglarlo.

Saludos,

Nicolás 

You should deleted the symbolic links that were created at ~/Library/Application\ Support/Glyphs/Scripts/ and then deleted the GlyphsScripts directory created at ~/Documents/GlyphsScripts/,
that is all.

If you want to deleted what was written in /etc/cron.d you only need to type in terminal 

sudo rm /private/etc/cron.d/sync_git_repos
and put your user password. This step is automatic when you try to install again.

**Comment by zar-nicolas20** [comment]
Because some script have the same name and other are organized as a compliment of plugins, I will not reorder by myself the symbolic links. @MajusCorp If you indicate me which script in which folder I could make a custom plugin structure for you.
