### ISSUE TITLE
Add me to the Repos

### ISSUE THREAD

**Issue by Nevu** [zar-nicolas20/GlyphsApp-Package-Install#2]
Hi Nicolas,

maybe you could add my Repo to the Set.

Look at this: https://github.com/Nevu/IconFont

G O

**Comment by zar-nicolas20** [comment]
Hi Nevu,

Nice, I will add it on Thursday.

Best,

Nicolás

**Comment by zar-nicolas20** [comment]
I will add your repo on the weekend, tomorrow I won't have time.

Best,

**Comment by zar-nicolas20** [comment]
Ready @Nevu, sorry for the delay. Let me know if I need to fix something
