### ISSUE TITLE
Update Script Package

### ISSUE THREAD

**Issue by Nevu** [zar-nicolas20/GlyphsApp-Package-Install#3]
Hello,

Sorry for the inconvenience. I just addes some new Scripts and merged the Packages for better handling. Maybe you have to update your Repo.

Thx

**Comment by zar-nicolas20** [comment]
Hi Nevu, yes, I will update the script, thanks for notifying me.

Best,

Nicolás

**Comment by zar-nicolas20** [comment]
Hi Nevu,

I have updated the address of your repo, please try this new version and let me know if it is not working as expected.

I will close this issue because your repos have been updated.

Thanks,

Nicolás
