### ISSUE TITLE
Scripts y plugins

### ISSUE THREAD

**Issue by guidoferreyra** [zar-nicolas20/GlyphsApp-Package-Install#4]
Hola Nicolás. Tengo algunos pequeños scripts y dos plugins, tal vez sean útiles para alguien más ademas de mi. Si te parece relevante tal vez los podes agregar al Package Install.

Pego los links aquí debajo.
https://github.com/guidoferreyra/Glyphs-Scripts
https://github.com/guidoferreyra/ShowNextFont
https://github.com/guidoferreyra/ShowNextFontAnchors

Saludos!!

**Comment by zar-nicolas20** [comment]
Muchas gracias Guido!

Los voy a agregar, tengo varios en lista de espera.

Saludos,

Nicolás

**Comment by zar-nicolas20** [comment]
Hola Guido, Por fin llego el día para agregar tus repositorios, te notificaré cuando este actualizado el bash Script.
Saludos,

**Comment by guidoferreyra** [comment]
Genial Nicolás. Justo acabo de agregar otro pequeño plugin.

Saludos!

**Comment by zar-nicolas20** [comment]
He agregado los siguientes:
- [GuidoFerreyra Glyphs-Scripts](https://github.com/guidoferreyra/Glyphs-Scripts)
- [GuidoFerreyra ShowNextFont](https://github.com/guidoferreyra/ShowNextFont)
- [GuidoFerreyra ShowNextFontAnchors](https://github.com/guidoferreyra/ShowNextFontAnchors)
- [GuidoFerreyra showAnchorCoordinates](https://github.com/guidoferreyra/showAnchorCoordinates)

Dime si son son todos.

Aún no subo los cambios locales al repositorio porque necesito probar que no haya bugs en el nuevo código.

**Comment by guidoferreyra** [comment]
Hay un plugin más que es show coordinates que es como tener la herramienta
de medición constantemente activada pero con la distancia de los
manejadores también

**Comment by zar-nicolas20** [comment]
Bien, lo agrego, avisame si encuentras algo que no funcione como esperas.

Gracias por tu colaboración.

Nicolás
