### ISSUE TITLE
2 recently created repos

### ISSUE THREAD

**Issue by drawcard** [zar-nicolas20/GlyphsApp-Package-Install#5]
Hi,

Thanks for this amazing script. Here are two new worthwhile repos to add:
https://github.com/mekkablue/ShowItalic
https://github.com/schriftgestalt/ShowTopsAndBottoms

:+1: :smile:

**Comment by zar-nicolas20** [comment]
Thanks I will add this two new repositories to the bash script.

Best,

**Comment by zar-nicolas20** [comment]
Your changes were added to the current repo. Please check the new files and confirm is it is working as expected.

Thanks again.

**Comment by zar-nicolas20** [comment]
I will close this issue because your changes were added to the master brach. I suggest to update your branch.

Best,

Nicolás
