### ISSUE TITLE
Nevu's repo cannot be found

### ISSUE THREAD

**Issue by drawcard** [zar-nicolas20/GlyphsApp-Package-Install#6]
Hi,

Nevu's repo (https://github.com/Nevu/IconFont.git) is showing a 404 not found error and is causing the config script to fail (asking for github credentials to fetch the repo).

Output when running the script is:

``` bash
Cloning into 'Nevu_Scripts'...
Username for 'https://github.com': 
Password for 'https://xxxxxx@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/Nevu/IconFont.git/' not found
GlyphsScriptsConfi.sh: line 794: cd: Nevu_Scripts: No such file or directory
===================================
Done Nevu's Scripts
===================================
Finished Glyphs Scripts setup
```

`GlyphsScriptsConfi.sh: line 794: cd: Nevu_Scripts: No such file or directory` seems to be where the problem lies.

**Comment by drawcard** [comment]
@Nevu ^^

**Comment by zar-nicolas20** [comment]
Hi, @ Nevu wrote me that he have change his repository. I will update its path and public a new shell script today. Thanks for the notification.

Best,

**Comment by drawcard** [comment]
Awesome, thanks!

**Comment by zar-nicolas20** [comment]
Please check the new files and confirm is it is working as expected.

Thanks

**Comment by Nevu** [comment]
Could you solve the problem? I still can't see my scripts directory ; ) (https://github.com/Nevu/ScriptsForGlyphs_Nevu)

By the way thanks for this bundle

**Comment by zar-nicolas20** [comment]
Hi @Nevu ,

I am able to see your script either in the Application as in the documentation and the [script](https://github.com/zar-nicolas20/GlyphsApp-Package-Install/blob/master/GlyphsScriptsConfi.sh#L814-L820).

Have you download the latest?

Best,

Nicolás

![screen shot 2016-01-19 at 9 27 42 am](https://cloud.githubusercontent.com/assets/3999974/12426582/30ead822-be8f-11e5-9349-6fe990363a36.png)
![screen shot 2016-01-19 at 9 28 09 am](https://cloud.githubusercontent.com/assets/3999974/12426583/30ed4346-be8f-11e5-9e49-cebf3715ca32.png)
